### ISSUE TITLE
I have a some problems with the user creation on Twitch 

### ISSUE THREAD

**Issue by GameFather92** [Kappador/salamoonder-api#1]
When I tried generate a new user on Twitch, with a custom username, the library response me that the username is use already but is not true, this is a problem and I think that the current validation is with  404 status but Twitch never will response with status 404, please I need an update to create users because is imposible with the current configuration. 

When I try to create custom users, all of them are always answered by the API that are already in use. @Kappador

**Comment by Kappador** [comment]
Hey, there have been quite a lot of updates on https://salamoonder.com , but none of them affect this library. The library still works flawlessly on my end. Please add some code snippets so I can investigate this further and help you out.

![Code_F9ptoBwiwE](https://github.com/Kappador/salamoonder/assets/64945579/7b67c662-02d6-44e2-9a00-c7dde719c230)
![Code_HjNLn7rUtZ](https://github.com/Kappador/salamoonder/assets/64945579/ea36632d-8702-4320-b872-de4c82bc660b)
![Code_QGBNq8z5E2](https://github.com/Kappador/salamoonder/assets/64945579/8594001d-c100-43c6-93ff-fd7e4c141b5b)

**Comment by GameFather92** [comment]
Thank you for the responde, but your examples were with email, I need validate the username, is most important to me. Do you have any example with username? @Kappador

**Comment by Kappador** [comment]
https://salamoonder.com does not allow you to provide a username, only a email. ([Documentation](https://apidocs.salamoonder.com/tasks/twitch/register-account)) 

However you can make your own account generator with this library and salamoonder, by using the basic captcha solving. The library provides you with a quick and easy way to generate `Passport Integrity Tokens`, which can be used on https://passport.twitch.tv to register an account.

Example:
![Code_LaAVFfknuv](https://github.com/Kappador/salamoonder/assets/64945579/323c247f-c7bd-431e-af39-4ef5db8bd6fe)
This is just an example, obviously I don't have the exact request on hand.
